### ISSUE TITLE
Dev Entrypoint database routine not working on Rails 6.1.x

### ISSUE THREAD

**Issue by vovimayhem** [IcaliaLabs/on-container-for-ruby#12]
On a plain, fresh Rails 6.1.x app, as long as we have `DATABASE_URL` defined in the environment, no extra changes to `config/database.yml` are required at all (the `production` config is another story, tho!)

However, our current suggested dev entrypoint fails to work unless we add the "url" option to the default config:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432') %> # <--- HERE
```

It would be GREAT if we do the same thing rails is doing, to avoid requiring this change to work in our dev environments.
